config/routes.rb
Rails.application.routes.draw do
  resources :sells
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :name, presence: true
    validates :price, presence: true

    has_many :sells

    after_create_commit :create_chart

    private 
        def create_chart
            broadcast_append_to(
                'books_charts_channel',
                partial: '/dashboard/charts/books/chart',
                locals: {book: self},
                target: 'books_charts'
            )
        end
end

app/models/sell.rb
class Sell < ApplicationRecord
  belongs_to :book
  validates :quantity, presence: true
  validates :day, presence: true

  after_create :set_total
  after_create_commit :update_charts

  DAYS = %w[MONDAY TUESDAY WEDNESDAY THURSDAY FRIDAY SATURDAY SUNDAY].freeze

  private 
    def set_total
      revenue = quantity * book.price
      self.update(total: revenue)
    end

    def update_charts
      broadcast_replace_to(
        'sells_charts_channel',
        partial: '/dashboard/charts/days/chart',
        locals: {},
        target: 'days_chart' 
      )
      broadcast_replace_to(
        'sells_charts_channel',
        partial: '/dashboard/charts/revenue/chart',
        locals: {},
        target: 'revenue_chart' 
      )
      broadcast_replace_to(
        'sells_charts_channel',
        partial: '/dashboard/charts/books/chart',
        locals: {book: book},
        target: "book_#{book.id}" 
      )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def new 
        @book = Book.new
    end

    def create 
        @book = Book.new book_params
        if  @book.save
            respond_to do |format|
                format.turbo_stream
            end
        else
            render :new, status: :unprocessable_entity
        end
    end

    private
        def book_params
            params.require(:book).permit(:name,:price)
        end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
    end
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
    before_action :set_book, only: %i[create]
    def new 
        @sell = Sell.new
    end

    def create
        @sell = @book.sells.new set_params
        if @sell.save
            respond_to do |format|
                format.turbo_stream
            end
        else
            render :new, status: :unprocessable_entity
        end
    end

    private
        def set_book
            @book = Book.find(params[:sell][:book_id])
        end

        def set_params
            params.require(:sell).permit(:quantity, :day)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper

    def latest_sells id
        array = Array.new
        Book.find(id).sells.each do |sell|
            array.push(sell.quantity)
        end
        array
    end

end

app/helpers/sells_helper.rb
module SellsHelper
    def sells_per_day
        array = Array.new
        Sell::DAYS.each do  |day|
            array.push([day,Sell.where(day: day).sum(:quantity)])
        end
        array
    end

    def revenue_from_sells
        array = Array.new
        Book.all.each do |book|
            array.push([book.name,book.sells.sum(:total).round(2)])
        end
        array
    end
end

app/views/books/_form.html.erb
<%= turbo_frame_tag 'new_record_component' do %>
    <div class="flex items-center w-full">
        <%= form_with(model: book, class: 'flex w-full items-center gap-2') do |form|%>
            <% if book.errors.any? %>
                <% book.errors.each do |error|%>
                    <span class="text-white"><%= error.full_message%></span>
                <% end %>
            <% end %>
            <div class="flex items-center gap-2">
                <%= form.label :name, class: 'font-semibold text-white'%>
                <%= form.text_field :name, class: 'font-semibold rounded p-2 text-xs'%>
            </div>
            <div class="flex items-center gap-2">
                <%= form.label :price, class: 'font-semibold text-white'%>
                <%= form.number_field :price, in: 1.0..100.0, step: :any, class: 'font-semibold rounded p-2 text-xs'%>
            </div>
            <div class="flex items-center justify-end gap-2 ml-5">
                <%= form.submit  class: 'font-semibold  p-2  bg-sky-600 text-sm  rounded text-white cursor-pointer'%>
                <%= link_to 'Cancel', :back, class: 'font-semibold p-2 bg-red-600 text-sm text-white rounded cursor-pointer'%>
            </div>
        <% end %>
    </div>
<% end %>

app/views/books/new.html.erb
<%= render 'form' , {book: @book} %>

app/views/dashboard/charts/books/_books.html.erb
<section class="flex flex-col w-full m-2 space-y-2 border">
    <h3 class="text-lg font-bold text-white">Sells by Book </h3>
    <div class="flex flex-col " id="books_charts">
        <% Book.all.each do |book|%>
            <%= render 'dashboard/charts/books/chart', book: book %>
        <% end %>
    </div>
</section>  

app/views/dashboard/charts/books/_chart.html.erb
<div id="book_<%=book.id%>" data-controller="book" data-books-sells="<%= latest_sells(book.id)%>" book-id="<%= book.id %>" class="m-2 bg-white">
    <canvas id="book_chart_<%=book.id%>" style="width:100%;max-width:700px"></canvas>
</div>

app/views/dashboard/charts/days/_chart.html.erb
<div data-controller="days" data-days-sells="<%= sells_per_day %>" id="days_chart" class="m-2">
    <canvas id="daySells" style="width:100%;max-width:700px"></canvas>
</div>

app/views/dashboard/charts/days/_days.html.erb
<section class="flex flex-col w-full border">
    <h3 class="text-lg font-bold text-white">Sells per Day </h3>
    <%= render 'dashboard/charts/days/chart' %>
</section>

app/views/dashboard/charts/revenue/_chart.html.erb
<div data-controller="revenue" data-revenue-sells="<%= revenue_from_sells %>" id="revenue_chart" class="m-2">
    <canvas id="revenueSells" style="width:100%;max-width:700px"></canvas>
    <div class="flex flex-col p-5 my-3 bg-white rounded">
        <h5 class="my-3 text-xl font-bold text-center">Sells per Book </h5>
        <table class="my-3">
            <div class="flex w-full">
                <div class="flex items-center justify-center w-1/3 text-sm font-semibold text-center border-2">ID</div>
                <div class="flex items-center justify-center w-1/3 text-sm font-semibold text-center border-2">Name</div>
                <div class="flex items-center justify-center w-1/3 text-sm font-semibold text-center border-2">Revenue</div>
            </div>
            <div class="flex flex-col">
                <% Book.all.each do |book|%>
                    <div class="flex">
                        <div class="flex items-center justify-center w-1/3 text-sm font-semibold text-center border-2"><%= book.id%></div>
                        <div class="flex items-center justify-center w-1/3 text-sm font-semibold text-center border-2"><%= book.name%></div>
                        <div class="flex items-center justify-center w-1/3 text-sm font-semibold text-center border-2"><%= book.sells.sum(:total).round(2)%> USD</div>
                    </div>
                <% end %>       
            </div>
        </table>
         <div class="flex justify-end">
            <p class="text-2xl font-bold">Total revenue:  <spam class="text-2xl font-normal"><%= Sell.all.sum(:total).round(2)%></spam> USD</p>
        </div>
    </div>
</div>

app/views/dashboard/charts/revenue/_revenue.html.erb
<section class="flex flex-col w-full border">
    <h3 class="text-lg font-bold text-white">Revenue</h3>
    <%= render 'dashboard/charts/revenue/chart' %>
</section>

app/views/dashboard/index.html.erb
<%= turbo_stream_from 'books_charts_channel'%>
<%= turbo_stream_from 'sells_charts_channel'%>
<main class="flex flex-col">
    <%= render 'shared/navbar' %>
    <section class="flex flex-col items-center justify-center w-full mt-20 mb-5 ">
        <div class="flex flex-col items-center">
            <h1 class="my-5 text-4xl font-bold text-white"> The BookStore App </h1>
        </div>
        <div class="flex w-full h-screen gap-5 border-4 border-gray-200">
            <%= render 'dashboard/charts/days/days'%>
            <%= render 'dashboard/charts/revenue/revenue'%>
            <%= render 'dashboard/charts/books/books'%> 
        </div>
    </section>  
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-black">
    <%= yield %>
  </body>
</html>

app/views/sells/_form.html.erb
<%= turbo_frame_tag 'new_record_component' do %>
    <div class="flex items-center w-full">
        <%= form_with(model: sell, class: 'flex w-full items-center gap-2') do |form|%>
            <% if sell.errors.any? %>
                <% sell.errors.each do |error|%>
                    <span class="text-white"><%= error.full_message%></span>
                <% end %>
            <% end %>
            <div class="flex items-center gap-2">
                 <%= form.label :book_id, 'Select book:',class: 'font-semibold text-white'%>
                 <%= form.select(:book_id, Book.all.collect {|book| [book.name, book.id]}, {include_blank: true},
                    class: 'font-semibold rounded p-2  text-xs'
                 )%>
            </div>

            <div class="flex items-center gap-2">
                <%= form.label :quantity, class: 'font-semibold text-white'%>
                <%= form.number_field :quantity, class: 'font-semibold rounded p-2 text-xs'%>
            </div>
            
             <div class="flex items-center gap-2">
                 <%= form.label :day, 'Select day:',class: 'font-semibold text-white'%>
                 <%= form.select(:day, Sell::DAYS.map {|day| [day.humanize, day]}, {include_blank: true},
                    class: 'font-semibold rounded p-2  text-xs'
                 )%>
            </div>
            
            <div class="flex items-center justify-end gap-2 ml-5">
                <%= form.submit  class: 'font-semibold  p-2  bg-sky-600 text-sm  rounded text-white cursor-pointer'%>
                <%= link_to 'Cancel', :back, class: 'font-semibold p-2 bg-red-600 text-sm text-white rounded cursor-pointer'%>
            </div>
        <% end %>
    </div>
<% end %>

app/views/sells/new.html.erb
<%= render 'form', sell: @sell%>

app/views/shared/_navbar.html.erb
<nav class="fixed flex items-center justify-between w-full p-5 bg-black">
    <div class="flex items-center gap-5">
        <%= image_tag('book_icon',class: 'w-12')%>
        <h3 class="text-lg font-bold text-white">The BookStore App</h3>
    </div>
    <div class="flex">
        <%= turbo_frame_tag 'new_record_component', class: 'flex gap-5' do %>
            <%= link_to new_sell_path, id: 'sell_link', class: 'text-white font-semibold text-sm text-center bg-green-700 text-white p-2 rounded cursor-pointer' do %>
                Add Sell 
            <% end %>
            
            <%= link_to new_book_path, id: 'book_link', class: 'text-white font-semibold text-sm text-center bg-blue-700 text-white p-2 rounded cursor-pointer' do %>
                Add New Book 
            <% end %>
        <% end %>
    </div>
</nav>